[package]
name = "awc"
version = "0.3.0"
authors = ["dandyvica <dandyvica@gmail.com>"]
edition = "2018"

[dependencies]
flate2 = "1.0.14"
clap = "3.0.0-beta.2"

[target.'cfg(windows)'.dependencies]
glob = "0.3.0"

[[bin]]
name = "genutf"
path = "tests/genutf.rs"

